# Generated by Django 3.0.8 on 2020-07-29 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anx', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='writings',
            new_name='posts',
        ),
        migrations.RenameField(
            model_name='posts',
            old_name='name',
            new_name='username',
        ),
    ]
